package main

var defaultConfig = Configuration{
	Models: []Model{
		{
			Name:     "Gemini",
			Model:    "gemini-pro",
			APIKey:   "",
			BaseURL:  "https://generativelanguage.googleapis.com/v1beta",
			Inactive: true,
			Default:  false,
		},
		{
			Name:     "Gemini",
			Model:    "gemini-1.0-pro-latest",
			APIKey:   "",
			BaseURL:  "https://generativelanguage.googleapis.com/v1beta",
			Inactive: true,
			Default:  false,
		},
		{
			Name:     "Gemini",
			Model:    "gemini-1.0-pro",
			APIKey:   "",
			BaseURL:  "https://generativelanguage.googleapis.com/v1beta",
			Inactive: true,
			Default:  false,
		},
		{
			Name:     "OpenAI",
			Model:    "gpt-4",
			APIKey:   "",
			BaseURL:  "https://api.openai.com/v1",
			Inactive: true,
			Default:  false,
		},
		{
			Name:     "OpenAI",
			Model:    "gpt-3.5-turbo",
			APIKey:   "",
			BaseURL:  "https://api.openai.com/v1",
			Inactive: true,
			Default:  false,
		},
		{
			Name:     "OpenAI",
			Model:    "gpt-4-turbo-preview",
			APIKey:   "",
			BaseURL:  "https://api.openai.com/v1",
			Inactive: true,
			Default:  false,
		},
		{
			Name:     "Mistral",
			Model:    "mistral-small-latest",
			APIKey:   "",
			BaseURL:  "https://api.mistral.ai/v1",
			Inactive: true,
			Default:  false,
		},
		{
			Name:     "Mistral",
			Model:    "mistral-medium-latest",
			APIKey:   "",
			BaseURL:  "https://api.mistral.ai/v1",
			Inactive: true,
			Default:  false,
		},
		{
			Name:     "Mistral",
			Model:    "mistral-large-latest",
			APIKey:   "",
			BaseURL:  "https://api.mistral.ai/v1",
			Inactive: true,
			Default:  false,
		},
		{
			Name:     "Anthropic",
			Model:    "claude-3-opus-20240229",
			APIKey:   "",
			BaseURL:  "https://api.anthropic.com/v1",
			Inactive: true,
			Default:  false,
		},
		{
			Name:     "Anthropic",
			Model:    "claude-3-sonnet-20240229",
			APIKey:   "",
			BaseURL:  "https://api.anthropic.com/v1",
			Inactive: true,
			Default:  false,
		},
		{
			Name:     "Anthropic",
			Model:    "claude-3-haiku-20240307",
			APIKey:   "",
			BaseURL:  "https://api.anthropic.com/v1",
			Inactive: true,
			Default:  false,
		},
		{
			Name:     "Ollama",
			Model:    "starcoder2:15b",
			BaseURL:  "http://localhost:11434",
			Inactive: true,
			Default:  false,
		},
	},
	Prompts: []Prompt{
		{Topic: "ALL", Prompt: "I want you to act as a world-class software developer with decades of experience in %%FILETYPE%%.\nI will ask you for output, and you have to give me unique, expertly written work.\nWrite comments for all functions and data structures."},
		{Topic: "EXPLAIN", Prompt: "Explain, in detail, the returned code. Explain why you made the choices you did and why I would want to do it this way."},
		{Topic: "NOEXPLAIN", Prompt: "Return only code with no explainations except code comments."},
		{Topic: "go", Prompt: ""},
		{Topic: "react", Prompt: ""},
		{Topic: "ts", Prompt: ""},
	},
}
